services:
    postgres:
        image: postgres
        container_name: PostgreSQL
        restart: unless-stopped
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: Hieudo@831
            POSTGRES_DB: pccms
        ports:
            - "17284:5432"
        volumes:
            - postgres_data:/var/lib/postgresql

volumes:
    postgres_data: